import { db } from "@workspace/db";
import {
  connectionsTable,
  suggestedConnectionsTable,
  profilesTable,
  placementsTable,
  feedPostsTable,
  eventsTable,
  projectsTable,
} from "@workspace/db/schema";

async function seed() {
  console.log("Seeding database...");

  await db.delete(connectionsTable);
  await db.delete(suggestedConnectionsTable);
  await db.delete(profilesTable);
  await db.delete(placementsTable);
  await db.delete(feedPostsTable);
  await db.delete(eventsTable);
  await db.delete(projectsTable);

  await db.insert(connectionsTable).values([
    {
      name: "Aryan Sharma",
      university: "IIT Bombay",
      major: "Computer Science",
      year: "3rd Year",
      skills: ["React", "Machine Learning", "Python"],
      avatarInitials: "AS",
      mutualConnections: 12,
      connectedSince: "Jan 2026",
    },
    {
      name: "Priya Nair",
      university: "NIT Trichy",
      major: "Electronics & Communication",
      year: "4th Year",
      skills: ["Embedded Systems", "IoT", "C++"],
      avatarInitials: "PN",
      mutualConnections: 7,
      connectedSince: "Feb 2026",
    },
    {
      name: "Rohan Mehta",
      university: "BITS Pilani",
      major: "Software Engineering",
      year: "2nd Year",
      skills: ["TypeScript", "Node.js", "Docker"],
      avatarInitials: "RM",
      mutualConnections: 19,
      connectedSince: "Dec 2025",
    },
    {
      name: "Kavya Reddy",
      university: "IIT Delhi",
      major: "Data Science",
      year: "3rd Year",
      skills: ["PyTorch", "Data Analysis", "SQL"],
      avatarInitials: "KR",
      mutualConnections: 5,
      connectedSince: "Mar 2026",
    },
    {
      name: "Aarav Patel",
      university: "VIT Vellore",
      major: "Cybersecurity",
      year: "4th Year",
      skills: ["Penetration Testing", "Network Security", "Rust"],
      avatarInitials: "AP",
      mutualConnections: 9,
      connectedSince: "Nov 2025",
    },
  ]);

  await db.insert(suggestedConnectionsTable).values([
    {
      name: "Sneha Kapoor",
      university: "IIT Madras",
      major: "AI & Robotics",
      year: "3rd Year",
      skills: ["PyTorch", "ROS", "Computer Vision"],
      avatarInitials: "SK",
      matchScore: 94,
      matchReasons: ["Both studying AI", "Shared interest in robotics", "Same graduation year"],
      mutualConnections: 8,
    },
    {
      name: "Dev Malhotra",
      university: "IIT Kharagpur",
      major: "Computer Science",
      year: "3rd Year",
      skills: ["React", "GraphQL", "Go"],
      avatarInitials: "DM",
      matchScore: 91,
      matchReasons: ["Both working with React", "Attending same hackathon", "Mutual friends"],
      mutualConnections: 14,
    },
    {
      name: "Ishaan Verma",
      university: "IIIT Hyderabad",
      major: "Product Design",
      year: "2nd Year",
      skills: ["Figma", "UX Research", "Prototyping"],
      avatarInitials: "IV",
      matchScore: 88,
      matchReasons: ["Both interested in product", "Design collaboration potential", "Cross-domain match"],
      mutualConnections: 3,
    },
    {
      name: "Nisha Gupta",
      university: "IIT Roorkee",
      major: "Biotechnology",
      year: "4th Year",
      skills: ["Bioinformatics", "Python", "Research"],
      avatarInitials: "NG",
      matchScore: 82,
      matchReasons: ["Interdisciplinary projects", "Research opportunities", "2 mutual connections"],
      mutualConnections: 2,
    },
    {
      name: "Siddharth Joshi",
      university: "NIT Warangal",
      major: "Mechanical Engineering",
      year: "3rd Year",
      skills: ["CAD Design", "Python", "IoT"],
      avatarInitials: "SJ",
      matchScore: 79,
      matchReasons: ["Hardware + software crossover", "Same project category", "3 mutual connections"],
      mutualConnections: 3,
    },
    {
      name: "Ananya Singh",
      university: "IIT Bombay",
      major: "Finance & Technology",
      year: "4th Year",
      skills: ["Fintech", "Blockchain", "Data Analysis"],
      avatarInitials: "ANS",
      matchScore: 86,
      matchReasons: ["Both building fintech projects", "Same campus", "Active in same clubs"],
      mutualConnections: 11,
    },
  ]);

  await db.insert(profilesTable).values([
    {
      name: "Meera Iyer",
      university: "IIT Madras",
      major: "Computer Science & Design",
      year: "3rd Year",
      bio: "Building products at the intersection of design and engineering. Currently working on an AR campus map.",
      skills: ["Figma", "React Native", "Swift", "UX Research"],
      avatarInitials: "MI",
      connections: 143,
      openToCollaborate: true,
    },
    {
      name: "Karan Bhatia",
      university: "BITS Goa",
      major: "Economics & Computer Science",
      year: "4th Year",
      bio: "Quantitative research meets software. Interning at DE Shaw this summer. Open to fintech projects.",
      skills: ["Python", "Quant Finance", "Machine Learning", "R"],
      avatarInitials: "KB",
      connections: 289,
      openToCollaborate: true,
    },
    {
      name: "Tanya Khanna",
      university: "IIT Delhi",
      major: "Electrical Engineering",
      year: "2nd Year",
      bio: "Competing in robotics nationals next month. Passionate about autonomous systems and edge computing.",
      skills: ["FPGA", "Embedded C", "ROS", "Raspberry Pi"],
      avatarInitials: "TK",
      connections: 76,
      openToCollaborate: false,
    },
    {
      name: "Aditya Rao",
      university: "IIT Hyderabad",
      major: "Data Science",
      year: "3rd Year",
      bio: "Published a paper on attention mechanisms in NLP. Building an open-source library for ML engineers.",
      skills: ["PyTorch", "NLP", "Research", "Python"],
      avatarInitials: "AR",
      connections: 198,
      openToCollaborate: true,
    },
    {
      name: "Pooja Menon",
      university: "NIT Calicut",
      major: "Information Technology",
      year: "3rd Year",
      bio: "Full-stack dev who loves building products fast. 3 apps launched, 0 regrets. Let's ship something.",
      skills: ["Next.js", "PostgreSQL", "TypeScript", "AWS"],
      avatarInitials: "PM",
      connections: 167,
      openToCollaborate: true,
    },
    {
      name: "Vikram Sinha",
      university: "IIT Kanpur",
      major: "Aerospace Engineering",
      year: "4th Year",
      bio: "Satellite projects, drone racing, and simulation. Building the future of UAV tech with my team.",
      skills: ["MATLAB", "Python", "Aerodynamics", "Control Systems"],
      avatarInitials: "VS",
      connections: 112,
      openToCollaborate: false,
    },
  ]);

  await db.insert(placementsTable).values([
    {
      studentName: "Rahul Verma",
      university: "IIT Bombay",
      company: "Google",
      role: "Software Engineer",
      package: "45 LPA",
      type: "fulltime",
      month: "March 2026",
      avatarInitials: "RV",
      isVerified: true,
    },
    {
      studentName: "Shreya Agarwal",
      university: "IIT Delhi",
      company: "Microsoft",
      role: "Product Manager",
      package: "38 LPA",
      type: "fulltime",
      month: "March 2026",
      avatarInitials: "SA",
      isVerified: true,
    },
    {
      studentName: "Abhishek Nair",
      university: "BITS Pilani",
      company: "Stripe",
      role: "Software Engineer Intern",
      package: "12 LPA",
      type: "internship",
      month: "February 2026",
      avatarInitials: "AN",
      isVerified: true,
    },
    {
      studentName: "Divya Krishnan",
      university: "IIT Madras",
      company: "Anthropic",
      role: "AI Research Engineer",
      package: "52 LPA",
      type: "fulltime",
      month: "March 2026",
      avatarInitials: "DK",
      isVerified: true,
    },
    {
      studentName: "Nikhil Jain",
      university: "NIT Trichy",
      company: "Zepto",
      role: "Backend Engineer",
      package: "22 LPA",
      type: "fulltime",
      month: "February 2026",
      avatarInitials: "NJ",
      isVerified: false,
    },
    {
      studentName: "Priya Singh",
      university: "IIT Roorkee",
      company: "Atlassian",
      role: "Software Development Engineer",
      package: "32 LPA",
      type: "fulltime",
      month: "January 2026",
      avatarInitials: "PS",
      isVerified: true,
    },
    {
      studentName: "Arjun Mehra",
      university: "IIT Kharagpur",
      company: "Apple",
      role: "iOS Engineer Intern",
      package: "15 LPA",
      type: "internship",
      month: "February 2026",
      avatarInitials: "AM",
      isVerified: true,
    },
    {
      studentName: "Sakshi Rao",
      university: "IIIT Hyderabad",
      company: "Razorpay",
      role: "Frontend Engineer",
      package: "24 LPA",
      type: "fulltime",
      month: "January 2026",
      avatarInitials: "SR",
      isVerified: false,
    },
    {
      studentName: "Tanmay Bhatt",
      university: "VIT Vellore",
      company: "Amazon",
      role: "SDE Intern",
      package: "10 LPA",
      type: "internship",
      month: "March 2026",
      avatarInitials: "TB",
      isVerified: true,
    },
    {
      studentName: "Ritika Sharma",
      university: "IIT Bombay",
      company: "Meta",
      role: "Data Scientist",
      package: "41 LPA",
      type: "fulltime",
      month: "March 2026",
      avatarInitials: "RS",
      isVerified: true,
    },
  ]);

  await db.insert(feedPostsTable).values([
    {
      authorName: "Elena Rodriguez",
      authorUniversity: "Stanford",
      authorMajor: "Computer Science",
      avatarInitials: "ER",
      content: "Just finished my first hackathon! Huge thanks to my team for pulling through 48 hours of no sleep. We built an AI tool for summarizing lecture notes. Anyone want to beta test it?",
      likes: 124,
      comments: 18,
      timeAgo: "2h ago",
      tags: ["hackathon", "AI", "buildInPublic"],
    },
    {
      authorName: "Kabir Desai",
      authorUniversity: "IIT Bombay",
      authorMajor: "Computer Science",
      avatarInitials: "KD",
      content: "Looking for a UI/UX designer to collaborate on my startup idea — a peer tutoring marketplace for college students. We already have 200 signups from our campus. DM me if interested!",
      likes: 89,
      comments: 31,
      timeAgo: "5h ago",
      tags: ["startup", "collaboration", "design"],
    },
    {
      authorName: "Anushka Verma",
      authorUniversity: "NIT Trichy",
      authorMajor: "Electronics",
      avatarInitials: "AV",
      content: "Placement season has been wild. 3 rejections, 2 referrals that went nowhere, and then — Google called. Don't give up. The right door opens.",
      likes: 412,
      comments: 67,
      timeAgo: "1d ago",
      tags: ["placements", "motivation"],
    },
    {
      authorName: "Aryan Menon",
      authorUniversity: "BITS Goa",
      authorMajor: "Software Engineering",
      avatarInitials: "AM",
      content: "Shipped my first open source project — a CLI tool that generates TypeScript types from SQL schemas. 47 GitHub stars in 2 days. Building in public is underrated.",
      likes: 203,
      comments: 29,
      timeAgo: "3h ago",
      tags: ["openSource", "TypeScript", "buildInPublic"],
    },
  ]);

  await db.insert(eventsTable).values([
    {
      title: "Intro to Web3 Development",
      organizer: "Blockchain Club",
      date: "Thursday",
      time: "6:00 PM",
      location: "Lecture Hall 4, IIT Bombay",
      attendees: 127,
      category: "Workshop",
      description: "Learn Solidity, deploy your first smart contract, and understand the DeFi ecosystem from core builders.",
    },
    {
      title: "Startup Weekend 2026",
      organizer: "E-Cell IIT Delhi",
      date: "April 12–14",
      time: "9:00 AM",
      location: "Main Auditorium",
      attendees: 340,
      category: "Hackathon",
      description: "54 hours to go from idea to MVP. Form teams, find mentors, and pitch to investors on day 3.",
    },
    {
      title: "AI in Healthcare Panel",
      organizer: "MedTech Society",
      date: "Friday",
      time: "3:30 PM",
      location: "Seminar Room B, IIIT Hyderabad",
      attendees: 89,
      category: "Panel",
      description: "Researchers and practitioners discuss the real-world applications of AI in diagnostics, drug discovery, and patient care.",
    },
  ]);

  await db.insert(projectsTable).values([
    {
      title: "CampusMap AR",
      description: "An augmented reality campus navigation app that helps freshers find classrooms, labs, and hostels in real-time. Looking for iOS and Unity developers.",
      authorName: "Meera Iyer",
      university: "IIT Madras",
      techStack: ["Unity", "ARKit", "Swift", "Firebase"],
      rolesNeeded: ["iOS Developer", "Unity Developer", "UI Designer"],
      teamSize: 4,
      currentMembers: 1,
      status: "open",
    },
    {
      title: "PeerTutor",
      description: "A verified marketplace for peer-to-peer tutoring on campus. Students can book sessions with top rankers in any subject. Revenue share model.",
      authorName: "Kabir Desai",
      university: "IIT Bombay",
      techStack: ["Next.js", "PostgreSQL", "Stripe", "TypeScript"],
      rolesNeeded: ["Backend Developer", "UI/UX Designer"],
      teamSize: 3,
      currentMembers: 1,
      status: "open",
    },
    {
      title: "Placement Intel",
      description: "A data-driven platform aggregating real placement statistics from campus ambassadors. Salary ranges, interview experiences, and company-specific prep.",
      authorName: "Sneha Joshi",
      university: "BITS Pilani",
      techStack: ["React", "Python", "FastAPI", "PostgreSQL"],
      rolesNeeded: ["Full Stack Developer", "Data Analyst"],
      teamSize: 5,
      currentMembers: 3,
      status: "in-progress",
    },
  ]);

  console.log("Seed complete!");
}

seed().catch(console.error);
